(library
 (name frontend)
 (libraries mopsa.mopsa_c_parser utils apron))

(ocamllex
 (modules Lexer PropertyLexer PropertyLexerNew CTLPropertyLexer))

(menhir
 (modules Parser PropertyParser PropertyParserNew CTLPropertyParser))

(env
 (dev
  (flags
   (:standard -w -9-27-32-33-35 -warn-error -A))))
