name: Log Diff Check

on:
  pull_request:
  push:

jobs:
  diff-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout tree
        uses: actions/checkout@v5

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4

      - run: opam install . --deps-only

      - run: opam exec -- dune build


      - name: Generate logs
        run: |
          mkdir -p logs_new
          bash script/logs.bash main.exe logs_new

      - name: Run diff script
        run: |
          python3 script/function-diff.py logs logs_new
